# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sportzballz-baseball

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1

functions:
  ashburn-picks:
    handler: src.ashburn.main
    timeout: 90
    environment:
      SPORTSPAGE_API_KEY: ${env:SPORTSPAGE_API_KEY}
      SLACK_TOKEN: ${env:SLACK_TOKEN}
      MODEL: 'ashburn'
  bowa-picks:
    handler: src.bowa.main
    timeout: 90
    environment:
      SPORTSPAGE_API_KEY: ${env:SPORTSPAGE_API_KEY}
      SLACK_TOKEN: ${env:SLACK_TOKEN}
      MODEL: 'bowa'
  carlton-picks:
    handler: src.carlton.main
    timeout: 90
    environment:
      SPORTSPAGE_API_KEY: ${env:SPORTSPAGE_API_KEY}
      SLACK_TOKEN: ${env:SLACK_TOKEN}
      MODEL: 'carlton'
  ashburn-backtest:
    handler: src.backtest.main
    timeout: 900
    environment:
      SPORTSPAGE_API_KEY: ${env:SPORTSPAGE_API_KEY}
      SLACK_TOKEN: ${env:SLACK_TOKEN}
      MODEL: 'ashburn'
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux